// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "ticket.proto" (package "ticket", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ticket.StreamAvailabilityRequest
 */
export interface StreamAvailabilityRequest {
    /**
     * @generated from protobuf field: string event_id = 1
     */
    eventId: string;
}
/**
 * @generated from protobuf message ticket.GetAvailabilityRequest
 */
export interface GetAvailabilityRequest {
    /**
     * @generated from protobuf field: string event_id = 1
     */
    eventId: string;
}
/**
 * Pushed to client on every reservation change
 *
 * @generated from protobuf message ticket.AvailabilityUpdate
 */
export interface AvailabilityUpdate {
    /**
     * @generated from protobuf field: string ticket_id = 1
     */
    ticketId: string;
    /**
     * @generated from protobuf field: string event_id = 2
     */
    eventId: string;
    /**
     * @generated from protobuf field: string tier_name = 3
     */
    tierName: string;
    /**
     * @generated from protobuf field: int32 available_quantity = 4
     */
    availableQuantity: number;
    /**
     * @generated from protobuf field: int32 total_quantity = 5
     */
    totalQuantity: number;
    /**
     * @generated from protobuf field: bool is_sold_out = 6
     */
    isSoldOut: boolean;
    /**
     * @generated from protobuf field: string updated_at = 7
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message ticket.AvailabilitySnapshot
 */
export interface AvailabilitySnapshot {
    /**
     * @generated from protobuf field: string event_id = 1
     */
    eventId: string;
    /**
     * @generated from protobuf field: repeated ticket.AvailabilityUpdate tiers = 2
     */
    tiers: AvailabilityUpdate[];
}
// @generated message type with reflection information, may provide speed optimized methods
class StreamAvailabilityRequest$Type extends MessageType<StreamAvailabilityRequest> {
    constructor() {
        super("ticket.StreamAvailabilityRequest", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamAvailabilityRequest>): StreamAvailabilityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventId = "";
        if (value !== undefined)
            reflectionMergePartial<StreamAvailabilityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamAvailabilityRequest): StreamAvailabilityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamAvailabilityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ticket.StreamAvailabilityRequest
 */
export const StreamAvailabilityRequest = new StreamAvailabilityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAvailabilityRequest$Type extends MessageType<GetAvailabilityRequest> {
    constructor() {
        super("ticket.GetAvailabilityRequest", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAvailabilityRequest>): GetAvailabilityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventId = "";
        if (value !== undefined)
            reflectionMergePartial<GetAvailabilityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAvailabilityRequest): GetAvailabilityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAvailabilityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ticket.GetAvailabilityRequest
 */
export const GetAvailabilityRequest = new GetAvailabilityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AvailabilityUpdate$Type extends MessageType<AvailabilityUpdate> {
    constructor() {
        super("ticket.AvailabilityUpdate", [
            { no: 1, name: "ticket_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tier_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "available_quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "total_quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "is_sold_out", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AvailabilityUpdate>): AvailabilityUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ticketId = "";
        message.eventId = "";
        message.tierName = "";
        message.availableQuantity = 0;
        message.totalQuantity = 0;
        message.isSoldOut = false;
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<AvailabilityUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvailabilityUpdate): AvailabilityUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ticket_id */ 1:
                    message.ticketId = reader.string();
                    break;
                case /* string event_id */ 2:
                    message.eventId = reader.string();
                    break;
                case /* string tier_name */ 3:
                    message.tierName = reader.string();
                    break;
                case /* int32 available_quantity */ 4:
                    message.availableQuantity = reader.int32();
                    break;
                case /* int32 total_quantity */ 5:
                    message.totalQuantity = reader.int32();
                    break;
                case /* bool is_sold_out */ 6:
                    message.isSoldOut = reader.bool();
                    break;
                case /* string updated_at */ 7:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AvailabilityUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ticket_id = 1; */
        if (message.ticketId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.ticketId);
        /* string event_id = 2; */
        if (message.eventId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventId);
        /* string tier_name = 3; */
        if (message.tierName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.tierName);
        /* int32 available_quantity = 4; */
        if (message.availableQuantity !== 0)
            writer.tag(4, WireType.Varint).int32(message.availableQuantity);
        /* int32 total_quantity = 5; */
        if (message.totalQuantity !== 0)
            writer.tag(5, WireType.Varint).int32(message.totalQuantity);
        /* bool is_sold_out = 6; */
        if (message.isSoldOut !== false)
            writer.tag(6, WireType.Varint).bool(message.isSoldOut);
        /* string updated_at = 7; */
        if (message.updatedAt !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ticket.AvailabilityUpdate
 */
export const AvailabilityUpdate = new AvailabilityUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AvailabilitySnapshot$Type extends MessageType<AvailabilitySnapshot> {
    constructor() {
        super("ticket.AvailabilitySnapshot", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tiers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AvailabilityUpdate }
        ]);
    }
    create(value?: PartialMessage<AvailabilitySnapshot>): AvailabilitySnapshot {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventId = "";
        message.tiers = [];
        if (value !== undefined)
            reflectionMergePartial<AvailabilitySnapshot>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvailabilitySnapshot): AvailabilitySnapshot {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                case /* repeated ticket.AvailabilityUpdate tiers */ 2:
                    message.tiers.push(AvailabilityUpdate.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AvailabilitySnapshot, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        /* repeated ticket.AvailabilityUpdate tiers = 2; */
        for (let i = 0; i < message.tiers.length; i++)
            AvailabilityUpdate.internalBinaryWrite(message.tiers[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ticket.AvailabilitySnapshot
 */
export const AvailabilitySnapshot = new AvailabilitySnapshot$Type();
/**
 * @generated ServiceType for protobuf service ticket.TicketGrpcService
 */
export const TicketGrpcService = new ServiceType("ticket.TicketGrpcService", [
    { name: "StreamAvailability", serverStreaming: true, options: {}, I: StreamAvailabilityRequest, O: AvailabilityUpdate },
    { name: "GetCurrentAvailability", options: {}, I: GetAvailabilityRequest, O: AvailabilitySnapshot }
]);
