// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "ticket.proto" (package "ticket", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TicketGrpcService } from "./ticket";
import type { AvailabilitySnapshot } from "./ticket";
import type { GetAvailabilityRequest } from "./ticket";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AvailabilityUpdate } from "./ticket";
import type { StreamAvailabilityRequest } from "./ticket";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Ticket gRPC Service
 * Provides server-streaming for real-time ticket availability updates.
 * Used by React client (via gRPC-Web) to show live remaining ticket count.
 *
 * @generated from protobuf service ticket.TicketGrpcService
 */
export interface ITicketGrpcServiceClient {
    /**
     * Stream ticket availability updates for a specific event.
     * Server pushes updates whenever a TicketReservedDomainEvent or TicketCancelledDomainEvent fires.
     *
     * @generated from protobuf rpc: StreamAvailability
     */
    streamAvailability(input: StreamAvailabilityRequest, options?: RpcOptions): ServerStreamingCall<StreamAvailabilityRequest, AvailabilityUpdate>;
    /**
     * @generated from protobuf rpc: GetCurrentAvailability
     */
    getCurrentAvailability(input: GetAvailabilityRequest, options?: RpcOptions): UnaryCall<GetAvailabilityRequest, AvailabilitySnapshot>;
}
/**
 * Ticket gRPC Service
 * Provides server-streaming for real-time ticket availability updates.
 * Used by React client (via gRPC-Web) to show live remaining ticket count.
 *
 * @generated from protobuf service ticket.TicketGrpcService
 */
export class TicketGrpcServiceClient implements ITicketGrpcServiceClient, ServiceInfo {
    typeName = TicketGrpcService.typeName;
    methods = TicketGrpcService.methods;
    options = TicketGrpcService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Stream ticket availability updates for a specific event.
     * Server pushes updates whenever a TicketReservedDomainEvent or TicketCancelledDomainEvent fires.
     *
     * @generated from protobuf rpc: StreamAvailability
     */
    streamAvailability(input: StreamAvailabilityRequest, options?: RpcOptions): ServerStreamingCall<StreamAvailabilityRequest, AvailabilityUpdate> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamAvailabilityRequest, AvailabilityUpdate>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCurrentAvailability
     */
    getCurrentAvailability(input: GetAvailabilityRequest, options?: RpcOptions): UnaryCall<GetAvailabilityRequest, AvailabilitySnapshot> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAvailabilityRequest, AvailabilitySnapshot>("unary", this._transport, method, opt, input);
    }
}
