using Dapper;
using Grpc.Core;
using LongPd.CleanArchitecture.Application.Abstractions.Data;

namespace LongPd.CleanArchitecture.Api.Grpc;

/// <summary>
/// gRPC service implementation for real-time ticket availability streaming.
/// React clients connect via gRPC-Web and receive push updates
/// whenever a TicketReservedDomainEvent or TicketCancelledDomainEvent fires.
///
/// Renamed to TicketGrpcServiceImpl to avoid naming collision with the static 
/// TicketGrpcService generated by Grpc.Tools compilation.
/// </summary>
public sealed class TicketGrpcServiceImpl(
    IDbConnectionFactory dbConnectionFactory,
    ILogger<TicketGrpcServiceImpl> logger)
    : TicketGrpcService.TicketGrpcServiceBase
{
    // Active streaming sessions: EventId → list of writers
    private static readonly Dictionary<Guid, List<IServerStreamWriter<AvailabilityUpdate>>> ActiveStreams = new();
    private static readonly Lock StreamLock = new();

    // Called by TicketReservedDomainEvent / TicketCancelledDomainEvent handlers
    public static async Task PushAvailabilityUpdate(Guid eventId, AvailabilityUpdate update)
    {
        List<IServerStreamWriter<AvailabilityUpdate>> writers;
        lock (StreamLock)
        {
            if (!ActiveStreams.TryGetValue(eventId, out var list)) return;
            writers = [..list]; // Snapshot to avoid lock during async write
        }

        var staleWriters = new List<IServerStreamWriter<AvailabilityUpdate>>();
        foreach (var writer in writers)
        {
            try
            {
                await writer.WriteAsync(update);
            }
            catch
            {
                staleWriters.Add(writer); // Client disconnected
            }
        }

        // Clean up disconnected clients
        if (staleWriters.Count > 0)
        {
            lock (StreamLock)
            {
                if (ActiveStreams.TryGetValue(eventId, out var list))
                    foreach (var stale in staleWriters) list.Remove(stale);
            }
        }
    }

    /// <summary>
    /// Server-streaming RPC — keeps connection open and pushes updates.
    /// Client subscribes once, receives updates until it disconnects.
    /// </summary>
    public override async Task StreamAvailability(
        StreamAvailabilityRequest request,
        IServerStreamWriter<AvailabilityUpdate> responseStream,
        ServerCallContext context)
    {
        if (!Guid.TryParse(request.EventId, out var eventId))
        {
            throw new RpcException(new Status(StatusCode.InvalidArgument, "Invalid EventId format."));
        }

        logger.LogInformation("[gRPC] Client subscribed to availability stream for EventId: {EventId}", eventId);

        // Register this stream
        lock (StreamLock)
        {
            if (!ActiveStreams.ContainsKey(eventId))
                ActiveStreams[eventId] = [];
            ActiveStreams[eventId].Add(responseStream);
        }

        // Send initial snapshot
        var snapshot = await GetCurrentSnapshotAsync(eventId, context.CancellationToken);
        foreach (var update in snapshot)
            await responseStream.WriteAsync(update, context.CancellationToken);

        // Keep stream alive until client disconnects
        try
        {
            await Task.Delay(Timeout.Infinite, context.CancellationToken);
        }
        catch (OperationCanceledException)
        {
            logger.LogInformation("[gRPC] Client disconnected from stream for EventId: {EventId}", eventId);
        }
        finally
        {
            // Unregister this stream
            lock (StreamLock)
            {
                if (ActiveStreams.TryGetValue(eventId, out var list))
                    list.Remove(responseStream);
            }
        }
    }

    /// <summary>Unary RPC — snapshot of current availability.</summary>
    public override async Task<AvailabilitySnapshot> GetCurrentAvailability(
        GetAvailabilityRequest request,
        ServerCallContext context)
    {
        if (!Guid.TryParse(request.EventId, out var eventId))
            throw new RpcException(new Status(StatusCode.InvalidArgument, "Invalid EventId."));

        var updates = await GetCurrentSnapshotAsync(eventId, context.CancellationToken);
        var snapshot = new AvailabilitySnapshot { EventId = request.EventId };
        snapshot.Tiers.AddRange(updates);
        return snapshot;
    }

    // ─── Private ──────────────────────────────────────────────────────────────
    private async Task<List<AvailabilityUpdate>> GetCurrentSnapshotAsync(Guid eventId, CancellationToken ct)
    {
        const string sql = """
            SELECT
                t."Id"::text              AS "TicketId",
                t."EventId"::text         AS "EventId",
                t."TierName",
                t."AvailableQuantity",
                t."TotalQuantity",
                (t."AvailableQuantity" = 0) AS "IsSoldOut"
            FROM "Tickets" t
            WHERE t."EventId" = @EventId AND t."IsDeleted" = false
            """;

        using var connection = dbConnectionFactory.Create();
        var rows = await connection.QueryAsync<TicketAvailabilityRow>(sql, new { EventId = eventId });

        return rows.Select(r => new AvailabilityUpdate
        {
            TicketId = r.TicketId,
            EventId = r.EventId,
            TierName = r.TierName,
            AvailableQuantity = r.AvailableQuantity,
            TotalQuantity = r.TotalQuantity,
            IsSoldOut = r.IsSoldOut,
            UpdatedAt = DateTime.UtcNow.ToString("O")
        }).ToList();
    }

    private sealed record TicketAvailabilityRow(
        string TicketId, string EventId, string TierName,
        int AvailableQuantity, int TotalQuantity, bool IsSoldOut);
}
